paths:
  dataset_dir_path: '/home/aaimscadmin/IRP_DATA/RescueNet/classifier_dataset'
  task: 'drone_damage'
  phases: 
    - 'train'
    - 'val'

original_data:
  root_dir: "/home/julian/datasets/RescueNet"
  train_directory: "/home/julian/datasets/RescueNet/train"
  val_directory: "/home/julian/datasets/RescueNet/val"
  label_folder_prefix: 'targets'
  label_file_suffix: 'lab'
  label_ext: 'png'
  gt_labels:
    - 'background'
    - 'water'
    - 'building_no_damage'
    - 'building_minor_damage'
    - 'building_major_damage'
    - 'building_destroyed'
    - 'vehicle'
    - 'road_clear'
    - 'road_blocked'
    - 'tree'
    - 'pool'
  patch_size: 256

model_training_parameters:
  wandb_project: 'post_disaster_classification'
  # classes_to_ignore:
  #   - no_damage
  # combine_classes: {
  #   "minor_damage" : "major_damage",
  #   "destroyed" : "major_damage"
  # }
  random_state: 42
  batch_size: 16
  num_epochs: 100
  learning_rate: 0.001

