paths:
  dataset_dir_path: '/home/aaimscadmin/IRP_DATA/RescueNet/classifier_dataset'
  task: 'drone_damage'
  phases: 
    - 'train'
    - 'val'
  evaluation_image_dir_path: '/home/aaimscadmin/IRP_DATA/RescueNet/val/val-org-img'
  evaluation_ground_truth_dir_path: '/home/aaimscadmin/IRP_DATA/RescueNet/val/val-label-img'
  evaluation_gt_labels:
    - 'background'
    - 'water'
    - 'building_no_damage'
    - 'building_minor_damage'
    - 'building_major_damage'
    - 'building_destroyed'
    - 'vehicle'
    - 'road_clear'
    - 'road_blocked'
    - 'tree'
    - 'pool'
  label_file_prefix: 'lab'

model_training_parameters:
  wandb_project: 'post_disaster_classification'
  classes_to_ignore:
    - background
    - pool
    - tree
    - vehicle 
    - water
    - road_clear
    - road_blocked
  test_size: 0.2
  random_state: 42
  batch_size: 16
  num_epochs: 100
  learning_rate: 0.0001
  permited_background_thresh: 0.8

