paths:
  dataset_dir_path: '/home/aaimscadmin/IRP_DATA/RescueNet/classifier_dataset'
  task: 'drone_damage'
  phases: 
    - 'train'
    - 'val'

original_data:
  root_dir: "/home/docsun/Datasets/RescueNet/blurred_multilabel_dataset"
  train_directory: "/home/julian/datasets/RescueNet/train"
  val_directory: "/home/julian/datasets/RescueNet/val"
  label_folder_prefix: 'targets'
  label_file_suffix: 'lab'
  label_ext: 'png'
  gt_labels:
    - 'background'
    - 'water'
    - 'building_no_damage'
    - 'building_minor_damage'
    - 'building_major_damage'
    - 'building_destroyed'
    - 'vehicle'
    - 'road_clear'
    - 'road_blocked'
    - 'tree'
    - 'pool'
  patch_size: 256

model_training_parameters:
  wandb_project: 'post_disaster_classification'
  classes_to_ignore:
    - background
    - water
    - vehicle
    - tree
    - pool
    - road_clear
    - road_blocked
  combine_classes: {
    "building_major_damage" : "building_destroyed",
    "building_minor_damage" : "building_no_damage"
  }
  random_state: 42
  batch_size: 16
  num_epochs: 100
  learning_rate: 0.0001

inference:
  model_path: "/home/julian/git-repo/juliangdz/GovernanceIRP/Autonomous-Governance-in-Disaster-Management/post_disaster_classification/drone_damage_saved_models/best_model.pth"