paths:
  dataset_dir_path: '/home/aaimscadmin/IRP_DATA/XBD/classifier_dataset'
  phases: 
    - 'train'
    - 'test'
  task: 'satellite_damage'
  evaluation_image_dir_path: '/home/aaimscadmin/IRP_DATA/XBD/classifier_dataset/test/images'
  evaluation_ground_truth_dir_path: '/home/aaimscadmin/IRP_DATA/XBD/classifier_dataset/test/targets'
  evaluation_gt_labels:
    - 'no_damage'
    - 'minor_damage'
    - 'major_damage'
    - 'destroyed'


model_training_parameters:
  wandb_project: 'post_disaster_classification'
  test_size: 0.3
  random_state: 42
  batch_size: 32
  num_epochs: 100
  learning_rate: 0.001
