paths:
  phases: 
    - 'train'
    - 'test'
  task: 'satellite_damage_vs_no_damage'

original_data:
  root_dir: "/home/julian/datasets/XBD/blurred_multilabel_dataset"
  train_directory: "/home/julian/datasets/XBD/train_images_labels_targets/train"
  val_directory: "/home/julian/datasets/XBD/test_images_labels_targets/test"
  label_folder_prefix: 'targets'
  label_file_suffix: 'target'
  label_ext: 'png'
  gt_labels:
    - 'no_damage'
    - 'minor_damage'
    - 'major_damage'
    - 'destroyed'
  patch_size: 256

model_training_parameters:
  wandb_project: 'post_disaster_classification'
  # classes_to_ignore:
    # - no_damage
  combine_classes: {
    "destroyed" : "major_damage",
    "minor_damage" : "major_damage"
  }
  random_state: 42
  batch_size: 16
  num_epochs: 100
  learning_rate: 0.001

inference:
  model_path: "/home/julian/git-repo/juliangdz/GovernanceIRP/Autonomous-Governance-in-Disaster-Management/post_disaster_classification/satellite_damage_vs_no_damage_saved_models/best_model.pth"