paths:
  dataset_dir_path: '/home/aaimscadmin/IRP_DATA/XBD/classifier_dataset'
  phases: 
    - 'train'
    - 'test'
  task: 'satellite_damage'
  evaluation_image_dir_path: '/home/aaimscadmin/IRP_DATA/XBD/classifier_dataset/test/images'
  evaluation_ground_truth_dir_path: '/home/aaimscadmin/IRP_DATA/XBD/classifier_dataset/test/targets'
  evaluation_gt_labels:
    - 'no_damage'
    - 'minor_damage'
    - 'major_damage'
    - 'destroyed'
  label_file_prefix: 'targets'

original_data:
  root_dir: "/home/aaimscadmin/IRP_DATA/XBD"
  train_directory: "/home/aaimscadmin/IRP_DATA/XBD/train_images_labels_targets/train"
  val_directory: "/home/aaimscadmin/IRP_DATA/XBD/test_images_labels_targets/test"
  label_folder_prefix: 'targets'
  label_file_suffix: 'target'
  gt_labels:
    - 'no_damage'
    - 'minor_damage'
    - 'major_damage'
    - 'destroyed'
  patch_size: 256

model_training_parameters:
  wandb_project: 'post_disaster_classification'
  classes_to_ignore:
    - 
  test_size: 0.3
  random_state: 42
  batch_size: 32
  num_epochs: 100
  learning_rate: 0.001
  permited_background_thresh: 0.8
