paths:
  tsv_files:
    - 'annotations/california_wildfires_final_data.tsv'
    - 'annotations/hurricane_harvey_final_data.tsv'
    - 'annotations/hurricane_irma_final_data.tsv'
    - 'annotations/hurricane_maria_final_data.tsv'
    - 'annotations/iraq_iran_earthquake_final_data.tsv'
    - 'annotations/mexico_earthquake_final_data.tsv'
    - 'annotations/srilanka_floods_final_data.tsv'
  task: 'info'
  dataset_dir_path: '/home/julian/datasets/crisis_mmd'
  glove_file: '/home/julian/datasets/glove_embeddings/glove.twitter.27B.100d.txt'

data:
  classes_to_drop:
    -

model_training_parameters:
  wandb_project: 'disaster_classification'
  vocab_size: 20000 
  max_seq_len: 20 # Varies per task
  test_size: 0.2
  random_state: 42
  batch_size: 4
  num_epochs: 100
  learning_rate: 0.0001
  hidden_dim: 128
  embedding_dim: 100
  image_size: [224, 224]

inference:
  model_path: "/home/julian/git-repo/juliangdz/GovernanceIRP/Autonomous-Governance-in-Disaster-Management/disaster_classification/agent_models/multimodal_info_saved_models/best_model.pth"
  train_csv: "/home/julian/git-repo/juliangdz/GovernanceIRP/Autonomous-Governance-in-Disaster-Management/quiz_application/scripts/data_logs/multimodal_logs/info/train_image_info_dataset.csv"
  val_csv: "/home/julian/git-repo/juliangdz/GovernanceIRP/Autonomous-Governance-in-Disaster-Management/quiz_application/scripts/data_logs/multimodal_logs/info/val_image_info_dataset.csv"
